name: spectrum_charts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

# flutter Launcer Icons for changing the app icon 
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#f5f2c9"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#f5f2c9"
    theme_color: "#f5f2c9"

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/icon/
